services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "127.0.0.1:9000:9000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.dfsprojekt.dk`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.routers.portainer.middlewares=my-geoblock@file"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock


  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    command:
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=simply"
      #- "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencrypt.acme.email=${EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.websecure.http.tls.certResolver=letsencrypt"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--experimental.plugins.geoblock.modulename=github.com/PascalMinder/geoblock"
      - "--experimental.plugins.geoblock.version=v0.2.8"
      - "--entrypoints.websecure.http.middlewares=my-geoblock@file"
      - "--providers.file.directory=/configuration"
      - "--providers.file.watch=true"


    environment:
      - DOPPLER_TOKEN
      - SIMPLY_API_KEY=${SIMPLY_API_KEY}
      - SIMPLY_ACCOUNT_NAME=${SIMPLY_ACCOUNT_NAME}
      - EMAIL=${EMAIL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - ./data/acme.json:/letsencrypt/acme.json
      - traefik-configurations:/configuration
      - /var/log/logfile.log:/var/logfile.log

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.dfsprojekt.dk`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"


  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    expose:
      - "3306"
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASS}
      MARIADB_ALLOW_EMPTY_PASSWORD: "no"
    volumes:
      - mariadb_data:/var/lib/mysql
      - mariadb_cnf:/etc/mysql/


  redis:
    image: redis:latest
    container_name: redis
    restart: always
    expose: 
      - "6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    tmpfs:
      - /data


  api:
    image: danielfs95/danielfsdocker:latest
    container_name: api
    restart: always
    depends_on:
      - db
      - redis
      - traefik
    expose:
      - 8000
    environment:
      - DOCKER_USERNAME=${DOCKER_USER}
      - DOCKER_PASSWORD=${DOCKER_PASS}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASS=${MARIADB_PASS}
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_PORT=${MARIADB_PORT}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.dfsprojekt.dk`)"
      - "traefik.http.routers.api.rule=PathPrefix(`/user`) || PathPrefix(`/tfa`) || PathPrefix(`/account`)" 
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.routers.api.middlewares=my-geoblock@file"
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://127.0.0.1:1514"
        tag: "api"


  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - REPO_USER=${DOCKER_USER}
      - REPO_PASS=${DOCKER_PASS}
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_CLEANUP=true
      #- WATCHTOWER_SCHEDULE=0 0 * * * *
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_POLL_INTERVAL=120 
    volumes:
      - /home/danielfs/docker/config.json:/config.json
      - /var/run/docker.sock:/var/run/docker.sock


volumes: 
  portainer_data:
  mariadb_data:
  mariadb_cnf:
  traefik-configurations: