name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          IMAGE_TAG=danielfs95/danielfsdocker:$(date +%s)
          docker build . --file Dockerfile --tag $IMAGE_TAG

      - name: Push the Docker image
        run: |
          echo "Pushing image: $IMAGE_TAG"
          docker push $IMAGE_TAG
