name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths: 
      - Docker/DBAPI.py
      - Docker/Dockerfile
  pull_request:
    branches: [ "master" ]
    paths: 
      - Docker/DBAPI.py
      - Docker/Dockerfile
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build ./Docker --file ./Docker/Dockerfile --tag danielfs95/danielfsdocker:latest

      - name: Push the Docker image
        run: docker push danielfs95/danielfsdocker:latest
